export const USER_TYPES = {
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    LOGIN_USER_START: 'LOGIN_USER_START',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
    SIGNUP_USER_START: 'SIGNUP_USER_START',
    SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
    SIGNUP_USER_FAILURE: 'SIGNUP_USER_FAILURE',
    SIGNOUT_USER_START: 'SIGNOUT_USER_START',
    SIGNOUT_USER_SUCCESS: 'SIGNOUT_USER_SUCCESS',
    SIGNOUT_USER_FAILURE: 'SIGNOUT_USER_FAILURE',
}
